library(ggplot2)
qplot(Sepal.Length, Petal.Length, data = iris, color = Species, size = Petal.Width, alpha = I(0.7))
graph2svg("ggplot2_plot.svg")
graph2pdf("ggplot2_plot.pdf")
graph2eps("ggplot2_plot.eps")
